version: "3"
services:

  mongo-banco:
    image: mongo:4
    networks:
      - shop-commerce
    restart: always
    ports:
      - "27017:27017"


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - shop-commerce
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    networks:
      - shop-commerce
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  user-service:
    image: user:1.0
    ports:
      - "8083:8083"
    networks:
      - shop-commerce
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-banco
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080

  produto-service:
    image: produto:1.0
    ports:
      - "8081:8081"
    networks:
      - shop-commerce
    depends_on:
      - user-service
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-banco
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
      

  compra-service:
    image: compra:1.0
    ports:
      - "8082:8082"
    networks:
      - shop-commerce
    depends_on:
      - user-service
      - produto-service
      - kafka
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-banco
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
      - KAFKA_ADDRESS=kafka:9092


networks:
  shop-commerce:
    driver: bridge