version: "3"
services:
  compra-api:
    image: docker.io/letscode/flux-server:latest
    ports:
      - "8381:8080"
    networks:
      - letscode-flux
    depends_on:
      - mongo-compra
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-compra
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080







  mongo-banco:
    image: mongo:4
    networks:
      - letscode-flux
    restart: always
    ports:
      - "27017:27017"


networks:
  letscode-flux: